#include "expose_class_constructors.h"

OOLUA_EXPORT_NO_FUNCTIONS(ParamConstructor)
OOLUA_EXPORT_NO_FUNCTIONS(TableRefConstructor)
OOLUA_EXPORT_NO_FUNCTIONS(WithOutConstructors)
OOLUA_EXPORT_NO_FUNCTIONS(LuaStateConstructors)
