#include "expose_class_constructors.h"

OOLUA_EXPORT_NO_FUNCTIONS(ParamConstructor)
OOLUA_EXPORT_NO_FUNCTIONS(TableRefConstructor)
OOLUA_EXPORT_NO_FUNCTIONS(WithOutConstructors)
OOLUA_EXPORT_NO_FUNCTIONS(LuaStateConstructors)
OOLUA_EXPORT_NO_FUNCTIONS(ConstructorThrowsStdException)
OOLUA_EXPORT_NO_FUNCTIONS(DefaultConstructorThrowsStdException)
